- name: install nginx
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install a Nginx Package
      yum:
        name: nginx
        state: present
    - name: Start nginx
      service:
        name: nginx
        state: started
